#
# Copyright 2017 NXP
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

EXTRA_CFLAGS += -Wall -g -D$(SOC)

ccflags-y += -I$(PWD)/../include/platform
obj-m := m4ctrl_dev.o
